export const userPetUrl = "http://localhost:8080/user"
export const matchMakingUrl = "http://localhost:8080/matchmaking"
export const forumUrl = "http://localhost:8080/forum"
export const chatUrl = "http://localhost:8080/messages"
export const likeUrl = "http://localhost:8080"
export const markedURL = "http://localhost:8080/marked-forum"
export const authUrl = "http://localhost:8080/user"
